### ISSUE TITLE
[META] phpList core phase 2

### ISSUE THREAD

**Issue by oliverklee** [phpList/phplist4-core#125]
This meta ticket covers the core-related tasks for phase 2. The base-distribution-specific tasks are listed in https://github.com/phpList/base-distribution/issues/18, the rest-api-specific tasks are listed in https://github.com/phpList/rest-api/issues/20, and the web-frontend-specific tasks are listed in https://github.com/phpList/web-frontend/issues/16.

- [x] #131 get the Travis builds to work on Trusty
- [x] #133, #138 rename the branch alias from 4.0.0-dev to 4.0.x-dev https://getcomposer.org/doc/articles/aliases.md#branch-alias
- [x] #135 add a .htaccess
- [x] #136 add the Symfony console
- [x] #139, #140 automatically determine the application root directory
- [x] debug logged routing exception (was the 404 error for the missing favicon)
- [x] #141 move the bin/ and web/ dir copying script to the core
- [x] #122 add favicons in different sizes (to avoid the 404 errors)
- [x] #145 fix error "You are not allowed to access this file." in development mode
- [x] #146 set up the log and cache directories
- [x] #148 move the environments to an interface
- [x] #134, #137, #147, #149 make the project structure more similar to the default Symfony project structure
- [x] #147, #149 clean up the configuration files
- [x] #150 add a server console command and document it
- [x] #150 document how to use the different environments
- [x] de-duplicate the director creation in the repositories
- [x] add a structure for a configuration file that is outside the vendor folder
- [x] #175 rename Bootstrap::preventProductionEnvironment
- [x] #151, #153, #158, #168 add a mechanism for modules to register themselves to the core via Composer
- [x] #168 document how to create/add modules
- [x] #168 remove the dependency on the REST bundle
- [x] #181 automatically clear and warm all caches on composer update
- [x] #182 document when to use the REST API and the repositories when writing modules
- [x] #180 configure the "hello world" route to only accept GET requests
- [x] #183 rename the "hello world" route
- [x] #183 make the root route an official "nothing is here yet" route
- [x] #183 rename ApplicationBundle to HelloWorld bundle
- [x] move the CI stuff into a shell script (or into several scripts)
- [x] #188, #189 move the production secret to environment variables or the "outside" configuration file
- [x] #190 add DB configuration via YAML files
- [x] #196 use the Symfony-Doctrine integration
- [x] #179, #205, #207 add DI and use it
- [x] #203 Allow modules to provide their own (non-service) configuration
- [x] #218 add a model and repository for lists
- [x] use the FOSRestBundle for rest-api
- [x] #223 add a model and repository for subscribers
- [x] allow setting the DB configuration via a configuration file in addition to environment variables
- [x] have a look at other systems and their APIs
- [x] #194, #235 Fix cache clearing for broken configurations
